name: roboshop-web
on:
  push:
  workflow_dispatch:
jobs:
  web-nginx:
    uses: linga-devsecops-actions/14.20.github-actions-roboshop-reusable-workflows/.github/workflows/web-nginx.yaml@main
    with:
      project: roboshop
      component: web
      environment: dev
      app_type: nginx
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
